version: "3.9"
services:
  db-mysql:
    image: mysql:8.0
    ports: 
      - "9000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Password123#@!
      - MYSQL_DATABASE=nest-sql
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql

volumes:
  db: